name: Build Gallery

on:
  push:
<<<<<<< HEAD
    paths:
      - 'test-app/**'
  pull_request:
=======
    branches: [ "main" ]
    paths:
      - 'test-app/**'
  pull_request:
    branches: [ "main" ]
>>>>>>> origin
    paths:
      - 'test-app/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # Ass WebAssembly target
    - name: Add wasm32 target
      run: rustup target add wasm32-unknown-unknown
      
    # Download and install trunk
    - name: Install trunk
      run: cargo install --locked trunk
      
    # Create an optimize build with trunk
    - name: Build WASM
      run: cd test-app && trunk --config Trunk.prod.toml build --release
    
    # Commit and push
    - name: Commit files
      run: |
        git config --local user.email "finnbearone@gmail.com"
        git config --local user.name "Yew Icons"
        git commit -a -m "Build Gallery"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
