name: Build Gallery

on:
  push:
    paths:
      - 'test-app/**'
      - '.github/workflows/cd.yml'
  pull_request:
    paths:
      - 'test-app/**'
      - '.github/workflows/cd.yml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    # Ass WebAssembly target
    - name: Add wasm32 target
      run: rustup target add wasm32-unknown-unknown
      
    # Download and install trunk
    - name: Install cargo-hack
      uses: baptiste0928/cargo-install@v2
      with:
        crate: trunk
      
    # Create an optimize build with trunk
    - name: Build WASM
      run: cd test-app && trunk --config Trunk.prod.toml build --release
    
    # Commit and push
    - name: Commit files
      run: |
        git config --local user.email "finnbearone@gmail.com"
        git config --local user.name "Yew Icons"
        git commit -a -m "Build Gallery"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
